DROP TABLE ODONTOLOGOS IF EXISTS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT,1234,'MAYREN','SILVA'),
(DEFAULT, 1222, 'ALDEMAR','BOHORQUEZ');